spring.application.name=eureka-server

server.port=8761

# Since this is the registry itself, don't register it as a client
eureka.client.register-with-eureka=false

# Don't fetch registry information from another Eureka server
eureka.client.fetch-registry=false